// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Wetrip.Data.Entities;

namespace Wetrip.Data.DBContext;

public partial class WeTripContext : DbContext
{
    public WeTripContext()
    {
    }

    public WeTripContext(DbContextOptions<WeTripContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<CompanionTrip> CompanionTrips { get; set; }

    public virtual DbSet<ConfirmedGroup> ConfirmedGroups { get; set; }

    public virtual DbSet<ConfirmedGroupMember> ConfirmedGroupMembers { get; set; }

    public virtual DbSet<ConfirmedGroupMessage> ConfirmedGroupMessages { get; set; }

    public virtual DbSet<ConfirmedGroupMessageLocation> ConfirmedGroupMessageLocations { get; set; }

    public virtual DbSet<ConfirmedGroupMessageMedium> ConfirmedGroupMessageMedia { get; set; }

    public virtual DbSet<ConfirmedGroupMessageText> ConfirmedGroupMessageTexts { get; set; }

    public virtual DbSet<Flight> Flights { get; set; }

    public virtual DbSet<FlightBooking> FlightBookings { get; set; }

    public virtual DbSet<Hashtag> Hashtags { get; set; }

    public virtual DbSet<Hotel> Hotels { get; set; }

    public virtual DbSet<HotelBooking> HotelBookings { get; set; }

    public virtual DbSet<Like> Likes { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<PostHashtag> PostHashtags { get; set; }

    public virtual DbSet<PostMedium> PostMedia { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SavedPost> SavedPosts { get; set; }

    public virtual DbSet<SharedPost> SharedPosts { get; set; }

    public virtual DbSet<TaggedUser> TaggedUsers { get; set; }

    public virtual DbSet<TemporaryGroup> TemporaryGroups { get; set; }

    public virtual DbSet<TemporaryGroupMember> TemporaryGroupMembers { get; set; }

    public virtual DbSet<TemporaryGroupMessage> TemporaryGroupMessages { get; set; }

    public virtual DbSet<TemporaryGroupMessageLocation> TemporaryGroupMessageLocations { get; set; }

    public virtual DbSet<TemporaryGroupMessageMedium> TemporaryGroupMessageMedia { get; set; }

    public virtual DbSet<TemporaryGroupMessageText> TemporaryGroupMessageTexts { get; set; }

    public virtual DbSet<TourGuide> TourGuides { get; set; }

    public virtual DbSet<TourGuideBooking> TourGuideBookings { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserFollow> UserFollows { get; set; }

    public virtual DbSet<Wallet> Wallets { get; set; }

    /*protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-0BE7JLH6\\SQLEXPRESS;Initial Catalog=WeTrip;User ID=sa;Password=12345;Encrypt=False");*/
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {

        if (!optionsBuilder.IsConfigured)
        {

            var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            string ConnectionStr = config.GetConnectionString("DefaultConnectionStringDB");

            optionsBuilder.UseSqlServer(ConnectionStr);
        }

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__Comments__C3B4DFAA1458B088");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ParentCommentId).HasColumnName("ParentCommentID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.UserCommentedId).HasColumnName("UserCommentedID");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .HasConstraintName("FK__Comments__Parent__52593CB8");

            entity.HasOne(d => d.Post).WithMany(p => p.Comments)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Comments__PostID__5441852A");

            entity.HasOne(d => d.UserCommented).WithMany(p => p.Comments)
                .HasForeignKey(d => d.UserCommentedId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Comments__UserCo__5535A963");
        });

        modelBuilder.Entity<CompanionTrip>(entity =>
        {
            entity.HasKey(e => e.CompanionTripId).HasName("PK__Companio__002F56A96492ABF2");

            entity.ToTable("CompanionTrip");

            entity.Property(e => e.CompanionTripId).HasColumnName("CompanionTripID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.OwnerId).HasColumnName("OwnerID");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TravelCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TravelHoppy).HasMaxLength(255);
            entity.Property(e => e.TravelTime).HasColumnType("datetime");

            entity.HasOne(d => d.Owner).WithMany(p => p.CompanionTrips)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Companion__Owner__6FE99F9F");
        });

        modelBuilder.Entity<ConfirmedGroup>(entity =>
        {
            entity.HasKey(e => e.ConfirmedGroupId).HasName("PK__Confirme__DEED207811FC1807");

            entity.ToTable("ConfirmedGroup");

            entity.HasIndex(e => e.CompanionTripId, "UQ__Confirme__002F56A89014D71A").IsUnique();

            entity.Property(e => e.ConfirmedGroupId).HasColumnName("ConfirmedGroupID");
            entity.Property(e => e.CompanionTripId).HasColumnName("CompanionTripID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.CompanionTrip).WithOne(p => p.ConfirmedGroup)
                .HasForeignKey<ConfirmedGroup>(d => d.CompanionTripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Compa__0D7A0286");
        });

        modelBuilder.Entity<ConfirmedGroupMember>(entity =>
        {
            entity.HasKey(e => new { e.ConfirmedGroupId, e.UserId }).HasName("PK__Confirme__0F95ACB252B12E3D");

            entity.ToTable("ConfirmedGroupMember");

            entity.HasIndex(e => e.ConfirmedGroupId, "UQ__Confirme__DEED20797272B3D7").IsUnique();

            entity.Property(e => e.ConfirmedGroupId).HasColumnName("ConfirmedGroupID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.JoinAt).HasColumnType("datetime");

            entity.HasOne(d => d.ConfirmedGroup).WithOne(p => p.ConfirmedGroupMember)
                .HasForeignKey<ConfirmedGroupMember>(d => d.ConfirmedGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Confi__123EB7A3");

            entity.HasOne(d => d.User).WithMany(p => p.ConfirmedGroupMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__UserI__1332DBDC");
        });

        modelBuilder.Entity<ConfirmedGroupMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Confirme__C87C037CF248793F");

            entity.ToTable("ConfirmedGroupMessage");

            entity.HasIndex(e => e.GroupId, "UQ__Confirme__149AF30B965C04B9").IsUnique();

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.MessageType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.SentAt).HasColumnType("datetime");

            entity.HasOne(d => d.Group).WithOne(p => p.ConfirmedGroupMessage)
                .HasForeignKey<ConfirmedGroupMessage>(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Group__18EBB532");

            entity.HasOne(d => d.Sender).WithMany(p => p.ConfirmedGroupMessages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Sende__19DFD96B");
        });

        modelBuilder.Entity<ConfirmedGroupMessageLocation>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Confirme__C87C037C890B620D");

            entity.ToTable("ConfirmedGroupMessageLocation");

            entity.Property(e => e.MessageId)
                .ValueGeneratedNever()
                .HasColumnName("MessageID");

            entity.HasOne(d => d.Message).WithOne(p => p.ConfirmedGroupMessageLocation)
                .HasForeignKey<ConfirmedGroupMessageLocation>(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Messa__22751F6C");
        });

        modelBuilder.Entity<ConfirmedGroupMessageMedium>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Confirme__C87C037CBCCDC651");

            entity.Property(e => e.MessageId)
                .ValueGeneratedNever()
                .HasColumnName("MessageID");
            entity.Property(e => e.MediaUrl).HasMaxLength(500);

            entity.HasOne(d => d.Message).WithOne(p => p.ConfirmedGroupMessageMedium)
                .HasForeignKey<ConfirmedGroupMessageMedium>(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Messa__1F98B2C1");
        });

        modelBuilder.Entity<ConfirmedGroupMessageText>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Confirme__C87C037C8A34EF40");

            entity.ToTable("ConfirmedGroupMessageText");

            entity.Property(e => e.MessageId)
                .ValueGeneratedNever()
                .HasColumnName("MessageID");

            entity.HasOne(d => d.Message).WithOne(p => p.ConfirmedGroupMessageText)
                .HasForeignKey<ConfirmedGroupMessageText>(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Confirmed__Messa__1CBC4616");
        });

        modelBuilder.Entity<Flight>(entity =>
        {
            entity.HasKey(e => e.FlightId).HasName("PK__Flights__8A9E148E96CCA692");

            entity.Property(e => e.FlightId).HasColumnName("FlightID");
            entity.Property(e => e.Airline)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.DepartureTime).HasColumnType("datetime");
            entity.Property(e => e.FromLocation)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TicketClass).HasMaxLength(50);
            entity.Property(e => e.ToLocation)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<FlightBooking>(entity =>
        {
            entity.HasKey(e => e.FlightBookingId).HasName("PK__FlightBo__67A5D41B8D8F8C61");

            entity.Property(e => e.FlightBookingId).HasColumnName("FlightBookingID");
            entity.Property(e => e.BookedDate).HasColumnType("datetime");
            entity.Property(e => e.ConfirmedGroupId).HasColumnName("ConfirmedGroupID");
            entity.Property(e => e.FlightId).HasColumnName("FlightID");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ConfirmedGroup).WithMany(p => p.FlightBookings)
                .HasForeignKey(d => d.ConfirmedGroupId)
                .HasConstraintName("FK__FlightBoo__Confi__29221CFB");

            entity.HasOne(d => d.Flight).WithMany(p => p.FlightBookings)
                .HasForeignKey(d => d.FlightId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FlightBoo__Fligh__282DF8C2");

            entity.HasOne(d => d.User).WithMany(p => p.FlightBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FlightBoo__UserI__2739D489");
        });

        modelBuilder.Entity<Hashtag>(entity =>
        {
            entity.HasKey(e => e.HashtagId).HasName("PK__Hashtags__BEFA90CA83F24117");

            entity.Property(e => e.HashtagId).HasColumnName("HashtagID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Hotel>(entity =>
        {
            entity.HasKey(e => e.HotelId).HasName("PK__Hotels__46023BBFDBA3A20B");

            entity.Property(e => e.HotelId).HasColumnName("HotelID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.HotelName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ImageUrl).HasMaxLength(500);
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");
        });

        modelBuilder.Entity<HotelBooking>(entity =>
        {
            entity.HasKey(e => e.HotelBookingId).HasName("PK__HotelBoo__3653817293FAB808");

            entity.Property(e => e.HotelBookingId).HasColumnName("HotelBookingID");
            entity.Property(e => e.BookedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ConfirmedGroupId).HasColumnName("ConfirmedGroupID");
            entity.Property(e => e.HotelId).HasColumnName("HotelID");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ConfirmedGroup).WithMany(p => p.HotelBookings)
                .HasForeignKey(d => d.ConfirmedGroupId)
                .HasConstraintName("FK__HotelBook__Confi__30C33EC3");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelBookings)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HotelBook__Hotel__2FCF1A8A");

            entity.HasOne(d => d.User).WithMany(p => p.HotelBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HotelBook__UserI__2EDAF651");
        });

        modelBuilder.Entity<Like>(entity =>
        {
            entity.HasKey(e => e.LikeId).HasName("PK__Likes__A2922CF442795385");

            entity.Property(e => e.LikeId).HasColumnName("LikeID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.UserLikedId).HasColumnName("UserLikedID");

            entity.HasOne(d => d.Post).WithMany(p => p.Likes)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Likes__PostID__5CD6CB2B");

            entity.HasOne(d => d.UserLiked).WithMany(p => p.Likes)
                .HasForeignKey(d => d.UserLikedId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Likes__UserLiked__5DCAEF64");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E32A0642496");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Image).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__UserI__44FF419A");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Posts__AA126038B093C14F");

            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Title).HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Posts__UserID__48CFD27E");
        });

        modelBuilder.Entity<PostHashtag>(entity =>
        {
            entity.HasKey(e => new { e.PostId, e.HashtagId }).HasName("PK__PostHash__11FDC934D5C06DF5");

            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.HashtagId).HasColumnName("HashtagID");
            entity.Property(e => e.RawText).HasMaxLength(100);

            entity.HasOne(d => d.Hashtag).WithMany(p => p.PostHashtags)
                .HasForeignKey(d => d.HashtagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostHasht__Hasht__68487DD7");

            entity.HasOne(d => d.Post).WithMany(p => p.PostHashtags)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostHasht__PostI__6754599E");
        });

        modelBuilder.Entity<PostMedium>(entity =>
        {
            entity.HasKey(e => e.PostMediaId).HasName("PK__PostMedi__75C231142CBDC3E7");

            entity.Property(e => e.PostMediaId).HasColumnName("PostMediaID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.Post).WithMany(p => p.PostMedia)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PostMedia__PostI__4BAC3F29");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3AE16A28FB");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SavedPost>(entity =>
        {
            entity.HasKey(e => e.SavedPostId).HasName("PK__SavedPos__7B99A02B344E5967");

            entity.Property(e => e.SavedPostId).HasColumnName("SavedPostID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.UserSavedPostId).HasColumnName("UserSavedPostID");

            entity.HasOne(d => d.Post).WithMany(p => p.SavedPosts)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SavedPost__PostI__619B8048");

            entity.HasOne(d => d.UserSavedPost).WithMany(p => p.SavedPosts)
                .HasForeignKey(d => d.UserSavedPostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SavedPost__UserS__628FA481");
        });

        modelBuilder.Entity<SharedPost>(entity =>
        {
            entity.HasKey(e => e.SharedPostId).HasName("PK__SharedPo__C5B906C457A11B9B");

            entity.Property(e => e.SharedPostId).HasColumnName("SharedPostID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.UserSharedId).HasColumnName("UserSharedID");

            entity.HasOne(d => d.Post).WithMany(p => p.SharedPosts)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SharedPos__PostI__4E88ABD4");

            entity.HasOne(d => d.UserShared).WithMany(p => p.SharedPosts)
                .HasForeignKey(d => d.UserSharedId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SharedPos__UserS__4F7CD00D");
        });

        modelBuilder.Entity<TaggedUser>(entity =>
        {
            entity.HasKey(e => e.TaggedId).HasName("PK__TaggedUs__5B9F77412152BCDD");

            entity.Property(e => e.TaggedId).HasColumnName("TaggedID");
            entity.Property(e => e.PostId).HasColumnName("PostID");

            entity.HasOne(d => d.Post).WithMany(p => p.TaggedUsers)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TaggedUse__PostI__5812160E");

            entity.HasOne(d => d.UserTaggedNavigation).WithMany(p => p.TaggedUsers)
                .HasForeignKey(d => d.UserTagged)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TaggedUse__UserT__59063A47");
        });

        modelBuilder.Entity<TemporaryGroup>(entity =>
        {
            entity.HasKey(e => e.TemporaryGroupId).HasName("PK__Temporar__98C5852FDFA51EE0");

            entity.ToTable("TemporaryGroup");

            entity.HasIndex(e => e.CompanionTripId, "UQ__Temporar__002F56A88EB31124").IsUnique();

            entity.Property(e => e.TemporaryGroupId).HasColumnName("TemporaryGroupID");
            entity.Property(e => e.CompanionTripId).HasColumnName("CompanionTripID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.CompanionTrip).WithOne(p => p.TemporaryGroup)
                .HasForeignKey<TemporaryGroup>(d => d.CompanionTripId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Compa__74AE54BC");
        });

        modelBuilder.Entity<TemporaryGroupMember>(entity =>
        {
            entity.HasKey(e => new { e.TemporaryGroupId, e.UserId }).HasName("PK__Temporar__49BD09E5F092E111");

            entity.ToTable("TemporaryGroupMember");

            entity.HasIndex(e => e.TemporaryGroupId, "UQ__Temporar__98C5852E94490362").IsUnique();

            entity.Property(e => e.TemporaryGroupId).HasColumnName("TemporaryGroupID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.JoinAt).HasColumnType("datetime");

            entity.HasOne(d => d.TemporaryGroup).WithOne(p => p.TemporaryGroupMember)
                .HasForeignKey<TemporaryGroupMember>(d => d.TemporaryGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Tempo__797309D9");

            entity.HasOne(d => d.User).WithMany(p => p.TemporaryGroupMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__UserI__7A672E12");
        });

        modelBuilder.Entity<TemporaryGroupMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Temporar__C87C037CF6159F0C");

            entity.ToTable("TemporaryGroupMessage");

            entity.HasIndex(e => e.GroupId, "UQ__Temporar__149AF30B3871EB92").IsUnique();

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.MessageType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.SentAt).HasColumnType("datetime");

            entity.HasOne(d => d.Group).WithOne(p => p.TemporaryGroupMessage)
                .HasForeignKey<TemporaryGroupMessage>(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Group__00200768");

            entity.HasOne(d => d.Sender).WithMany(p => p.TemporaryGroupMessages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Sende__01142BA1");
        });

        modelBuilder.Entity<TemporaryGroupMessageLocation>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Temporar__C87C037CC8A423D1");

            entity.ToTable("TemporaryGroupMessageLocation");

            entity.Property(e => e.MessageId)
                .ValueGeneratedNever()
                .HasColumnName("MessageID");

            entity.HasOne(d => d.Message).WithOne(p => p.TemporaryGroupMessageLocation)
                .HasForeignKey<TemporaryGroupMessageLocation>(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Messa__09A971A2");
        });

        modelBuilder.Entity<TemporaryGroupMessageMedium>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Temporar__C87C037C9203A8BA");

            entity.Property(e => e.MessageId)
                .ValueGeneratedNever()
                .HasColumnName("MessageID");
            entity.Property(e => e.MediaUrl).HasMaxLength(500);

            entity.HasOne(d => d.Message).WithOne(p => p.TemporaryGroupMessageMedium)
                .HasForeignKey<TemporaryGroupMessageMedium>(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Messa__06CD04F7");
        });

        modelBuilder.Entity<TemporaryGroupMessageText>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Temporar__C87C037CC7C688E6");

            entity.ToTable("TemporaryGroupMessageText");

            entity.Property(e => e.MessageId)
                .ValueGeneratedNever()
                .HasColumnName("MessageID");

            entity.HasOne(d => d.Message).WithOne(p => p.TemporaryGroupMessageText)
                .HasForeignKey<TemporaryGroupMessageText>(d => d.MessageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Temporary__Messa__03F0984C");
        });

        modelBuilder.Entity<TourGuide>(entity =>
        {
            entity.HasKey(e => e.GuideId).HasName("PK__TourGuid__E77EE03EE518225D");

            entity.Property(e => e.GuideId)
                .ValueGeneratedNever()
                .HasColumnName("GuideID");
            entity.Property(e => e.Rating).HasColumnType("decimal(3, 2)");

            entity.HasOne(d => d.Guide).WithOne(p => p.TourGuide)
                .HasForeignKey<TourGuide>(d => d.GuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TourGuide__Guide__3587F3E0");
        });

        modelBuilder.Entity<TourGuideBooking>(entity =>
        {
            entity.HasKey(e => e.TourGuideBookingId).HasName("PK__TourGuid__DBA2C5AC643F4C71");

            entity.Property(e => e.TourGuideBookingId).HasColumnName("TourGuideBookingID");
            entity.Property(e => e.BookedDate).HasColumnType("datetime");
            entity.Property(e => e.GuideId).HasColumnName("GuideID");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Guide).WithMany(p => p.TourGuideBookings)
                .HasForeignKey(d => d.GuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TourGuide__Guide__3A4CA8FD");

            entity.HasOne(d => d.User).WithMany(p => p.TourGuideBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TourGuide__UserI__395884C4");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A4B32B88262");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Money).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.WalletId).HasColumnName("WalletID");

            entity.HasOne(d => d.Wallet).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.WalletId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Transacti__Walle__4222D4EF");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC2D58E8AF");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Avatar).HasMaxLength(500);
            entity.Property(e => e.BackgroundImage).HasMaxLength(500);
            entity.Property(e => e.Coin).HasDefaultValue(0);
            entity.Property(e => e.MembershipTier)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Personalityb).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleID__3A81B327");
        });

        modelBuilder.Entity<UserFollow>(entity =>
        {
            entity.HasKey(e => new { e.FollowerId, e.FollowingId }).HasName("PK__UserFoll__79CB03DB74982902");

            entity.Property(e => e.FollowerId).HasColumnName("FollowerID");
            entity.Property(e => e.FollowingId).HasColumnName("FollowingID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Follower).WithMany(p => p.UserFollowFollowers)
                .HasForeignKey(d => d.FollowerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserFollo__Follo__6B24EA82");

            entity.HasOne(d => d.Following).WithMany(p => p.UserFollowFollowings)
                .HasForeignKey(d => d.FollowingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserFollo__Follo__6C190EBB");
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.HasKey(e => e.WalletId).HasName("PK__Wallet__84D4F92E17A4F68A");

            entity.ToTable("Wallet");

            entity.HasIndex(e => e.UserId, "UQ__Wallet__1788CCAD40C3DF9C").IsUnique();

            entity.Property(e => e.WalletId).HasColumnName("WalletID");
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithOne(p => p.Wallet)
                .HasForeignKey<Wallet>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Wallet__UserID__3E52440B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}