// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wetrip.Data.Entities;

public partial class Flight
{
    public int FlightId { get; set; }

    public string Airline { get; set; }

    public string FromLocation { get; set; }

    public string ToLocation { get; set; }

    public DateTime DepartureTime { get; set; }

    public string TicketClass { get; set; }

    public decimal Price { get; set; }

    public int RemainingQuantity { get; set; }

    public virtual ICollection<FlightBooking> FlightBookings { get; set; } = new List<FlightBooking>();
}