// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wetrip.Data.Entities;

public partial class PostHashtag
{
    public int PostId { get; set; }

    public int HashtagId { get; set; }

    public string RawText { get; set; }

    public virtual Hashtag Hashtag { get; set; }

    public virtual Post Post { get; set; }
}