// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wetrip.Data.Entities;

public partial class UserFollow
{
    public int FollowerId { get; set; }

    public int FollowingId { get; set; }

    public DateOnly FollowedAt { get; set; }

    public DateOnly? UnfollowedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual User Follower { get; set; }

    public virtual User Following { get; set; }
}