// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wetrip.Data.Entities;

public partial class ConfirmedGroupMessageLocation
{
    public int MessageId { get; set; }

    public double Longitude { get; set; }

    public double Latitude { get; set; }

    public virtual ConfirmedGroupMessage Message { get; set; }
}