// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wetrip.Data.Entities;

public partial class PostMedium
{
    public int PostMediaId { get; set; }

    public string Url { get; set; }

    public int PostId { get; set; }

    public virtual Post Post { get; set; }
}