// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wetrip.Data.Entities;

public partial class TourGuideBooking
{
    public int TourGuideBookingId { get; set; }

    public int UserId { get; set; }

    public int GuideId { get; set; }

    public decimal Price { get; set; }

    public DateTime BookedDate { get; set; }

    public virtual TourGuide Guide { get; set; }

    public virtual User User { get; set; }
}